from typing import Protocol

from redis.asyncio import Redis
from sqlalchemy.ext.asyncio import AsyncSession


class DatabaseManagerProtocol(Protocol):
    async def connect(self) -> None: ...
    async def dispose(self) -> None: ...
    def session(self) -> AsyncSession: ...


class RedisManagerProtocol(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    def client(self) -> Redis: ...
